name: youtube
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^2.1.0
  built_collection: ^4.2.2
  built_value: ^6.7.0
  cupertino_icons: ^0.1.2
  flutter_bloc: ^0.21.0
  http: ^0.12.0+2
  tuple: ^1.0.2

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.7
  built_value_generator: ^6.7.0
  built_value_test: ^6.7.0

flutter:
  uses-material-design: true
